@extends('layouts.app')

@section('title', 'Mitigation Plans')

@php
    use App\Enums\FailureLogStatusEnum;
@endphp

@section('content')
    <main class="app-main">
        <!--begin::App Content Header-->
        <div class="app-content-header">
            <!--begin::Container-->
            <div class="container-fluid">
                <!--begin::Row-->
                <div class="row">
                    <div class="col-sm-6">
                        <h3 class="mb-0">Mitigation Plans</h3>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-end">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Mitigation Plans</li>
                        </ol>
                    </div>
                </div>
                <!--end::Row-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::App Content Header-->
        <!--begin::App Content-->
        <div class="app-content">
            <!--begin::Container-->
            <div class="container-fluid">
                <!--begin::Row-->
                <div class="row">
                    <div class="col-lg-12">
                        <!--begin::Accordion-->
                        <div class="card card-primary card-outline mb-4">
                            <!--begin::Header-->
                            <div class="card-header">
                                <div class="card-title">Mitigation Plans</div>
                            </div>
                            <!--end::Header-->
                            <!--begin::Body-->
                            <div class="card-body">
                                <div class="accordion" id="accordionExample">
                                    @foreach ($plans as $p)
                                        <div class="accordion-item">
                                            <h2 class="accordion-header">
                                                <button class="accordion-button collapsed" type="button"
                                                    data-bs-toggle="collapse"
                                                    data-bs-target="#collapse-{{ $loop->iteration }}" aria-expanded="false"
                                                    aria-controls="collapse-{{ $loop->iteration }}">
                                                    Root Cause: {{ Str::limit($p->root_cause, 30) }}
                                                </button>
                                            </h2>
                                            <div id="collapse-{{ $loop->iteration }}" class="accordion-collapse collapse"
                                                data-bs-parent="#accordionExample">
                                                <div class="accordion-body">
                                                    <div class="mb-2">
                                                        <small class="text-muted">
                                                            This analysis was generated by the Gemini 3 Flash Preview model
                                                            on {{ $p->created_at }}.
                                                        </small>
                                                        <br>
                                                        <small class="text-muted">Job ID: {{ $p->failureLog->id }}</small>
                                                    </div>
                                                    <div class="mb-2">
                                                        Error: {{ $p->failureLog->error }}
                                                        <br>
                                                        <small class="text-muted">Exception:
                                                            {{ $p->failureLog->exception }}</small>
                                                    </div>
                                                    <div class="alert alert-info" role="alert">
                                                        <b>Root Cause Analysis:</b> {{ $p->root_cause }}
                                                    </div>
                                                    <div>
                                                        <b>Contributing Factors:</b>
                                                        <ul>
                                                            @foreach ($p->contributing_factors as $factor)
                                                                <li>{{ $factor }}</li>
                                                            @endforeach
                                                        </ul>
                                                    </div>
                                                    <div>
                                                        <b>Mitigation Plans:</b>
                                                        <ul>
                                                            @foreach ($p->mitigation as $m)
                                                                <li>{{ $m }}</li>
                                                            @endforeach
                                                        </ul>
                                                    </div>
                                                    <div>
                                                        <b>Preventive Measure:</b>
                                                        <ul>
                                                            @foreach ($p->prevention as $pr)
                                                                <li>{{ $pr }}</li>
                                                            @endforeach
                                                        </ul>
                                                    </div>
                                                    <div class="btn-group" role="group">
                                                        <a href="{{ route('mp.resolved', ['id' => $p->failure_log_id]) }}"
                                                            class="btn btn-outline-primary resolve-btn">
                                                            Resolved
                                                        </a>
                                                        <a href="{{ route('mp.escalated', ['id' => $p->failure_log_id]) }}"
                                                            class="btn btn-outline-danger escalate-btn">
                                                            Escalate
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <!--end::Body-->
                        </div>
                        <!--end::Accordion-->
                    </div>
                </div>
                <!-- /.row (main row) -->
            </div>
            <!--end::Container-->
        </div>
        <!--end::App Content-->
    </main>
@endsection

@section('scripts')
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        $(document).on('click', '.resolve-btn', function(e) {
            e.preventDefault();

            const href = $(this).attr('href');

            Swal.fire({
                title: "Mark this incident as resolved?",
                text: "Are you sure you want to mark this incident as resolved?",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, mark as resolved",
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = href;
                }
            })
        });

        $(document).on('click', '.escalate-btn', function(e) {
            e.preventDefault();

            const href = $(this).attr('href');

            Swal.fire({
                title: "Mark this incident as escalated?",
                text: "By confirming, you acknowledge that this incident requires human intervention.",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, I understand",
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = href;
                }
            })
        });
    </script>
@endsection
